# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from sportmonks import Sportmonks

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        sportmonks = Sportmonks(
            # Defining the host is optional and defaults to https://api.sportmonks.com
            # See configuration.py for a list of all supported configuration parameters.
            host = "https://api.sportmonks.com",
            version = 'VERSION',
            sport = 'SPORT',
        
            # Configure API key authorization: apikeyAuth
            api_key = 'YOUR_API_KEY',
            # Uncomment below to setup prefix (e.g. Bearer) for API key, if needed
            # api_key_prefix = {'apikeyAuth': 'Bearer'},
        )
        self.assertIsNotNone(sportmonks)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
