/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


export * from './api/cities-api';
export * from './api/continents-api';
export * from './api/countries-api';
export * from './api/my-api';
export * from './api/odds-api';
export * from './api/regions-api';
export * from './api/sport-api';
export * from './api/types-api';

