# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.sport_schedules_by_season_id_response_subscription import SportSchedulesBySeasonIdResponseSubscription
from sportmonks import configuration


class TestSportSchedulesBySeasonIdResponseSubscription(unittest.TestCase):
    """SportSchedulesBySeasonIdResponseSubscription unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
