# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.sport_stage_by_id_response_data import SportStageByIdResponseData
from sportmonks import configuration


class TestSportStageByIdResponseData(unittest.TestCase):
    """SportStageByIdResponseData unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
