# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.sport_odds_pre_match_by_fixture_id_response_subscription_item_add_ons import SportOddsPreMatchByFixtureIdResponseSubscriptionItemAddOns
from sportmonks import configuration


class TestSportOddsPreMatchByFixtureIdResponseSubscriptionItemAddOns(unittest.TestCase):
    """SportOddsPreMatchByFixtureIdResponseSubscriptionItemAddOns unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
