# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.sport_leagues_search_response_subscription_item_plans import SportLeaguesSearchResponseSubscriptionItemPlans
from sportmonks import configuration


class TestSportLeaguesSearchResponseSubscriptionItemPlans(unittest.TestCase):
    """SportLeaguesSearchResponseSubscriptionItemPlans unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
