# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.sport_livescores_all_response_subscription import SportLivescoresAllResponseSubscription
from sportmonks import configuration


class TestSportLivescoresAllResponseSubscription(unittest.TestCase):
    """SportLivescoresAllResponseSubscription unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
