# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.countries_all_response_pagination import CountriesAllResponsePagination
from sportmonks import configuration


class TestCountriesAllResponsePagination(unittest.TestCase):
    """CountriesAllResponsePagination unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
