# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.sport_standings_live_by_league_id_response_subscription_item_add_ons_item import SportStandingsLiveByLeagueIdResponseSubscriptionItemAddOnsItem
from sportmonks import configuration


class TestSportStandingsLiveByLeagueIdResponseSubscriptionItemAddOnsItem(unittest.TestCase):
    """SportStandingsLiveByLeagueIdResponseSubscriptionItemAddOnsItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
