# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.sport_stages_search_response_subscription_item_plans_item import SportStagesSearchResponseSubscriptionItemPlansItem
from sportmonks import configuration


class TestSportStagesSearchResponseSubscriptionItemPlansItem(unittest.TestCase):
    """SportStagesSearchResponseSubscriptionItemPlansItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
