# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.sport_transfers_all_response_data import SportTransfersAllResponseData
from sportmonks import configuration


class TestSportTransfersAllResponseData(unittest.TestCase):
    """SportTransfersAllResponseData unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
