# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.sport_transfers_latest_response_pagination import SportTransfersLatestResponsePagination
from sportmonks import configuration


class TestSportTransfersLatestResponsePagination(unittest.TestCase):
    """SportTransfersLatestResponsePagination unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
