# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.sport_standings_all_response_pagination import SportStandingsAllResponsePagination
from sportmonks import configuration


class TestSportStandingsAllResponsePagination(unittest.TestCase):
    """SportStandingsAllResponsePagination unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
