# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.sport_venues_by_season_id_response_subscription_item import SportVenuesBySeasonIdResponseSubscriptionItem
from sportmonks import configuration


class TestSportVenuesBySeasonIdResponseSubscriptionItem(unittest.TestCase):
    """SportVenuesBySeasonIdResponseSubscriptionItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
