# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.continents_get_by_id_response_subscription_item_plans import ContinentsGetByIdResponseSubscriptionItemPlans
from sportmonks import configuration


class TestContinentsGetByIdResponseSubscriptionItemPlans(unittest.TestCase):
    """ContinentsGetByIdResponseSubscriptionItemPlans unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
