# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.odds_fixtures_upcoming_by_market_id_response import OddsFixturesUpcomingByMarketIdResponse
from sportmonks import configuration


class TestOddsFixturesUpcomingByMarketIdResponse(unittest.TestCase):
    """OddsFixturesUpcomingByMarketIdResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
