# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.cities_search_response_rate_limit import CitiesSearchResponseRateLimit
from sportmonks import configuration


class TestCitiesSearchResponseRateLimit(unittest.TestCase):
    """CitiesSearchResponseRateLimit unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
