# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.sport_squads_by_team_id_response_subscription_item_widgets import SportSquadsByTeamIdResponseSubscriptionItemWidgets
from sportmonks import configuration


class TestSportSquadsByTeamIdResponseSubscriptionItemWidgets(unittest.TestCase):
    """SportSquadsByTeamIdResponseSubscriptionItemWidgets unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
