# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sportmonks
from sportmonks.model.sport_venues_all_response_data_item import SportVenuesAllResponseDataItem
from sportmonks import configuration


class TestSportVenuesAllResponseDataItem(unittest.TestCase):
    """SportVenuesAllResponseDataItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
