/*
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sportmonks.Net.Api;
using Sportmonks.Net.Model;
using Sportmonks.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sportmonks.Net.Test.Model
{
    /// <summary>
    ///  Class for testing OddsMarketsSearchResponseDataInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OddsMarketsSearchResponseDataInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OddsMarketsSearchResponseDataInner
        //private OddsMarketsSearchResponseDataInner instance;

        public OddsMarketsSearchResponseDataInnerTests()
        {
            // TODO uncomment below to create an instance of OddsMarketsSearchResponseDataInner
            //instance = new OddsMarketsSearchResponseDataInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OddsMarketsSearchResponseDataInner
        /// </summary>
        [Fact]
        public void OddsMarketsSearchResponseDataInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" OddsMarketsSearchResponseDataInner
            //Assert.IsType<OddsMarketsSearchResponseDataInner>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'LegacyId'
        /// </summary>
        [Fact]
        public void LegacyIdTest()
        {
            // TODO unit test for the property 'LegacyId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DeveloperName'
        /// </summary>
        [Fact]
        public void DeveloperNameTest()
        {
            // TODO unit test for the property 'DeveloperName'
        }
        /// <summary>
        /// Test the property 'HasWinningCalculations'
        /// </summary>
        [Fact]
        public void HasWinningCalculationsTest()
        {
            // TODO unit test for the property 'HasWinningCalculations'
        }

    }

}
