/*
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sportmonks.Net.Api;
using Sportmonks.Net.Model;
using Sportmonks.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sportmonks.Net.Test.Model
{
    /// <summary>
    ///  Class for testing SportTvStationByIdResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SportTvStationByIdResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SportTvStationByIdResponseData
        //private SportTvStationByIdResponseData instance;

        public SportTvStationByIdResponseDataTests()
        {
            // TODO uncomment below to create an instance of SportTvStationByIdResponseData
            //instance = new SportTvStationByIdResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SportTvStationByIdResponseData
        /// </summary>
        [Fact]
        public void SportTvStationByIdResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" SportTvStationByIdResponseData
            //Assert.IsType<SportTvStationByIdResponseData>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'ImagePath'
        /// </summary>
        [Fact]
        public void ImagePathTest()
        {
            // TODO unit test for the property 'ImagePath'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'RelatedId'
        /// </summary>
        [Fact]
        public void RelatedIdTest()
        {
            // TODO unit test for the property 'RelatedId'
        }

    }

}
