/*
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sportmonks.Net.Api;
using Sportmonks.Net.Model;
using Sportmonks.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sportmonks.Net.Test.Model
{
    /// <summary>
    ///  Class for testing SportTransfersLatestResponseDataInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SportTransfersLatestResponseDataInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SportTransfersLatestResponseDataInner
        //private SportTransfersLatestResponseDataInner instance;

        public SportTransfersLatestResponseDataInnerTests()
        {
            // TODO uncomment below to create an instance of SportTransfersLatestResponseDataInner
            //instance = new SportTransfersLatestResponseDataInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SportTransfersLatestResponseDataInner
        /// </summary>
        [Fact]
        public void SportTransfersLatestResponseDataInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SportTransfersLatestResponseDataInner
            //Assert.IsType<SportTransfersLatestResponseDataInner>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'SportId'
        /// </summary>
        [Fact]
        public void SportIdTest()
        {
            // TODO unit test for the property 'SportId'
        }
        /// <summary>
        /// Test the property 'PlayerId'
        /// </summary>
        [Fact]
        public void PlayerIdTest()
        {
            // TODO unit test for the property 'PlayerId'
        }
        /// <summary>
        /// Test the property 'TypeId'
        /// </summary>
        [Fact]
        public void TypeIdTest()
        {
            // TODO unit test for the property 'TypeId'
        }
        /// <summary>
        /// Test the property 'FromTeamId'
        /// </summary>
        [Fact]
        public void FromTeamIdTest()
        {
            // TODO unit test for the property 'FromTeamId'
        }
        /// <summary>
        /// Test the property 'ToTeamId'
        /// </summary>
        [Fact]
        public void ToTeamIdTest()
        {
            // TODO unit test for the property 'ToTeamId'
        }
        /// <summary>
        /// Test the property 'PositionId'
        /// </summary>
        [Fact]
        public void PositionIdTest()
        {
            // TODO unit test for the property 'PositionId'
        }
        /// <summary>
        /// Test the property 'DetailedPositionId'
        /// </summary>
        [Fact]
        public void DetailedPositionIdTest()
        {
            // TODO unit test for the property 'DetailedPositionId'
        }
        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'CareerEnded'
        /// </summary>
        [Fact]
        public void CareerEndedTest()
        {
            // TODO unit test for the property 'CareerEnded'
        }
        /// <summary>
        /// Test the property 'Completed'
        /// </summary>
        [Fact]
        public void CompletedTest()
        {
            // TODO unit test for the property 'Completed'
        }
        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Fact]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }

    }

}
