/*
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sportmonks.Net.Api;
using Sportmonks.Net.Model;
using Sportmonks.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sportmonks.Net.Test.Model
{
    /// <summary>
    ///  Class for testing SportFixturesHeadToHeadResponseSubscriptionInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SportFixturesHeadToHeadResponseSubscriptionInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SportFixturesHeadToHeadResponseSubscriptionInner
        //private SportFixturesHeadToHeadResponseSubscriptionInner instance;

        public SportFixturesHeadToHeadResponseSubscriptionInnerTests()
        {
            // TODO uncomment below to create an instance of SportFixturesHeadToHeadResponseSubscriptionInner
            //instance = new SportFixturesHeadToHeadResponseSubscriptionInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SportFixturesHeadToHeadResponseSubscriptionInner
        /// </summary>
        [Fact]
        public void SportFixturesHeadToHeadResponseSubscriptionInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SportFixturesHeadToHeadResponseSubscriptionInner
            //Assert.IsType<SportFixturesHeadToHeadResponseSubscriptionInner>(instance);
        }


        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }
        /// <summary>
        /// Test the property 'Plans'
        /// </summary>
        [Fact]
        public void PlansTest()
        {
            // TODO unit test for the property 'Plans'
        }
        /// <summary>
        /// Test the property 'AddOns'
        /// </summary>
        [Fact]
        public void AddOnsTest()
        {
            // TODO unit test for the property 'AddOns'
        }
        /// <summary>
        /// Test the property 'Widgets'
        /// </summary>
        [Fact]
        public void WidgetsTest()
        {
            // TODO unit test for the property 'Widgets'
        }

    }

}
