/*
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sportmonks.Net.Api;
using Sportmonks.Net.Model;
using Sportmonks.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sportmonks.Net.Test.Model
{
    /// <summary>
    ///  Class for testing SportCoachesLatestResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SportCoachesLatestResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SportCoachesLatestResponse
        //private SportCoachesLatestResponse instance;

        public SportCoachesLatestResponseTests()
        {
            // TODO uncomment below to create an instance of SportCoachesLatestResponse
            //instance = new SportCoachesLatestResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SportCoachesLatestResponse
        /// </summary>
        [Fact]
        public void SportCoachesLatestResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SportCoachesLatestResponse
            //Assert.IsType<SportCoachesLatestResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Subscription'
        /// </summary>
        [Fact]
        public void SubscriptionTest()
        {
            // TODO unit test for the property 'Subscription'
        }
        /// <summary>
        /// Test the property 'RateLimit'
        /// </summary>
        [Fact]
        public void RateLimitTest()
        {
            // TODO unit test for the property 'RateLimit'
        }
        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Fact]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }

    }

}
