/*
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sportmonks.Net.Api;
using Sportmonks.Net.Model;
using Sportmonks.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sportmonks.Net.Test.Model
{
    /// <summary>
    ///  Class for testing SportNewsUpcomingPreMatchResponseDataInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SportNewsUpcomingPreMatchResponseDataInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SportNewsUpcomingPreMatchResponseDataInner
        //private SportNewsUpcomingPreMatchResponseDataInner instance;

        public SportNewsUpcomingPreMatchResponseDataInnerTests()
        {
            // TODO uncomment below to create an instance of SportNewsUpcomingPreMatchResponseDataInner
            //instance = new SportNewsUpcomingPreMatchResponseDataInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SportNewsUpcomingPreMatchResponseDataInner
        /// </summary>
        [Fact]
        public void SportNewsUpcomingPreMatchResponseDataInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SportNewsUpcomingPreMatchResponseDataInner
            //Assert.IsType<SportNewsUpcomingPreMatchResponseDataInner>(instance);
        }


        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'FixtureId'
        /// </summary>
        [Fact]
        public void FixtureIdTest()
        {
            // TODO unit test for the property 'FixtureId'
        }
        /// <summary>
        /// Test the property 'LeagueId'
        /// </summary>
        [Fact]
        public void LeagueIdTest()
        {
            // TODO unit test for the property 'LeagueId'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
