/*
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sportmonks.Net.Api;
using Sportmonks.Net.Model;
using Sportmonks.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sportmonks.Net.Test.Model
{
    /// <summary>
    ///  Class for testing SportPredictionsByFixtureIdResponseDataInnerPredictions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SportPredictionsByFixtureIdResponseDataInnerPredictionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SportPredictionsByFixtureIdResponseDataInnerPredictions
        //private SportPredictionsByFixtureIdResponseDataInnerPredictions instance;

        public SportPredictionsByFixtureIdResponseDataInnerPredictionsTests()
        {
            // TODO uncomment below to create an instance of SportPredictionsByFixtureIdResponseDataInnerPredictions
            //instance = new SportPredictionsByFixtureIdResponseDataInnerPredictions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SportPredictionsByFixtureIdResponseDataInnerPredictions
        /// </summary>
        [Fact]
        public void SportPredictionsByFixtureIdResponseDataInnerPredictionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SportPredictionsByFixtureIdResponseDataInnerPredictions
            //Assert.IsType<SportPredictionsByFixtureIdResponseDataInnerPredictions>(instance);
        }


        /// <summary>
        /// Test the property 'True'
        /// </summary>
        [Fact]
        public void TrueTest()
        {
            // TODO unit test for the property 'True'
        }
        /// <summary>
        /// Test the property 'False'
        /// </summary>
        [Fact]
        public void FalseTest()
        {
            // TODO unit test for the property 'False'
        }
        /// <summary>
        /// Test the property 'Scores'
        /// </summary>
        [Fact]
        public void ScoresTest()
        {
            // TODO unit test for the property 'Scores'
        }
        /// <summary>
        /// Test the property 'Home'
        /// </summary>
        [Fact]
        public void HomeTest()
        {
            // TODO unit test for the property 'Home'
        }
        /// <summary>
        /// Test the property 'Draw'
        /// </summary>
        [Fact]
        public void DrawTest()
        {
            // TODO unit test for the property 'Draw'
        }
        /// <summary>
        /// Test the property 'Away'
        /// </summary>
        [Fact]
        public void AwayTest()
        {
            // TODO unit test for the property 'Away'
        }

    }

}
