/*
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sportmonks.Net.Api;
using Sportmonks.Net.Model;
using Sportmonks.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sportmonks.Net.Test.Model
{
    /// <summary>
    ///  Class for testing SportStateByIdResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SportStateByIdResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SportStateByIdResponseData
        //private SportStateByIdResponseData instance;

        public SportStateByIdResponseDataTests()
        {
            // TODO uncomment below to create an instance of SportStateByIdResponseData
            //instance = new SportStateByIdResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SportStateByIdResponseData
        /// </summary>
        [Fact]
        public void SportStateByIdResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" SportStateByIdResponseData
            //Assert.IsType<SportStateByIdResponseData>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ShortName'
        /// </summary>
        [Fact]
        public void ShortNameTest()
        {
            // TODO unit test for the property 'ShortName'
        }
        /// <summary>
        /// Test the property 'DeveloperName'
        /// </summary>
        [Fact]
        public void DeveloperNameTest()
        {
            // TODO unit test for the property 'DeveloperName'
        }
        /// <summary>
        /// Test the property 'IsLive'
        /// </summary>
        [Fact]
        public void IsLiveTest()
        {
            // TODO unit test for the property 'IsLive'
        }
        /// <summary>
        /// Test the property 'IsPending'
        /// </summary>
        [Fact]
        public void IsPendingTest()
        {
            // TODO unit test for the property 'IsPending'
        }
        /// <summary>
        /// Test the property 'IsPeriodEnd'
        /// </summary>
        [Fact]
        public void IsPeriodEndTest()
        {
            // TODO unit test for the property 'IsPeriodEnd'
        }
        /// <summary>
        /// Test the property 'IsFinalState'
        /// </summary>
        [Fact]
        public void IsFinalStateTest()
        {
            // TODO unit test for the property 'IsFinalState'
        }
        /// <summary>
        /// Test the property 'IsCancelled'
        /// </summary>
        [Fact]
        public void IsCancelledTest()
        {
            // TODO unit test for the property 'IsCancelled'
        }
        /// <summary>
        /// Test the property 'IsFinalStandingState'
        /// </summary>
        [Fact]
        public void IsFinalStandingStateTest()
        {
            // TODO unit test for the property 'IsFinalStandingState'
        }
        /// <summary>
        /// Test the property 'IsCompleted'
        /// </summary>
        [Fact]
        public void IsCompletedTest()
        {
            // TODO unit test for the property 'IsCompleted'
        }
        /// <summary>
        /// Test the property 'TypeId'
        /// </summary>
        [Fact]
        public void TypeIdTest()
        {
            // TODO unit test for the property 'TypeId'
        }
        /// <summary>
        /// Test the property 'IsDeleted'
        /// </summary>
        [Fact]
        public void IsDeletedTest()
        {
            // TODO unit test for the property 'IsDeleted'
        }
        /// <summary>
        /// Test the property 'IsNotstarted'
        /// </summary>
        [Fact]
        public void IsNotstartedTest()
        {
            // TODO unit test for the property 'IsNotstarted'
        }
        /// <summary>
        /// Test the property 'SectionsActive'
        /// </summary>
        [Fact]
        public void SectionsActiveTest()
        {
            // TODO unit test for the property 'SectionsActive'
        }
        /// <summary>
        /// Test the property 'ScheduleOverrule'
        /// </summary>
        [Fact]
        public void ScheduleOverruleTest()
        {
            // TODO unit test for the property 'ScheduleOverrule'
        }

    }

}
