/*
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sportmonks.Net.Api;
using Sportmonks.Net.Model;
using Sportmonks.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sportmonks.Net.Test.Model
{
    /// <summary>
    ///  Class for testing SportOddsAllInPlayResponseSubscriptionInnerAddOnsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SportOddsAllInPlayResponseSubscriptionInnerAddOnsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SportOddsAllInPlayResponseSubscriptionInnerAddOnsInner
        //private SportOddsAllInPlayResponseSubscriptionInnerAddOnsInner instance;

        public SportOddsAllInPlayResponseSubscriptionInnerAddOnsInnerTests()
        {
            // TODO uncomment below to create an instance of SportOddsAllInPlayResponseSubscriptionInnerAddOnsInner
            //instance = new SportOddsAllInPlayResponseSubscriptionInnerAddOnsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SportOddsAllInPlayResponseSubscriptionInnerAddOnsInner
        /// </summary>
        [Fact]
        public void SportOddsAllInPlayResponseSubscriptionInnerAddOnsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SportOddsAllInPlayResponseSubscriptionInnerAddOnsInner
            //Assert.IsType<SportOddsAllInPlayResponseSubscriptionInnerAddOnsInner>(instance);
        }


        /// <summary>
        /// Test the property 'AddOn'
        /// </summary>
        [Fact]
        public void AddOnTest()
        {
            // TODO unit test for the property 'AddOn'
        }
        /// <summary>
        /// Test the property 'Sport'
        /// </summary>
        [Fact]
        public void SportTest()
        {
            // TODO unit test for the property 'Sport'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }

    }

}
