/*
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sportmonks.Net.Api;
using Sportmonks.Net.Model;
using Sportmonks.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sportmonks.Net.Test.Model
{
    /// <summary>
    ///  Class for testing SportFixturesByDateResponseRateLimit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SportFixturesByDateResponseRateLimitTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SportFixturesByDateResponseRateLimit
        //private SportFixturesByDateResponseRateLimit instance;

        public SportFixturesByDateResponseRateLimitTests()
        {
            // TODO uncomment below to create an instance of SportFixturesByDateResponseRateLimit
            //instance = new SportFixturesByDateResponseRateLimit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SportFixturesByDateResponseRateLimit
        /// </summary>
        [Fact]
        public void SportFixturesByDateResponseRateLimitInstanceTest()
        {
            // TODO uncomment below to test "IsType" SportFixturesByDateResponseRateLimit
            //Assert.IsType<SportFixturesByDateResponseRateLimit>(instance);
        }


        /// <summary>
        /// Test the property 'ResetsInSeconds'
        /// </summary>
        [Fact]
        public void ResetsInSecondsTest()
        {
            // TODO unit test for the property 'ResetsInSeconds'
        }
        /// <summary>
        /// Test the property 'Remaining'
        /// </summary>
        [Fact]
        public void RemainingTest()
        {
            // TODO unit test for the property 'Remaining'
        }
        /// <summary>
        /// Test the property 'RequestedEntity'
        /// </summary>
        [Fact]
        public void RequestedEntityTest()
        {
            // TODO unit test for the property 'RequestedEntity'
        }

    }

}
