/*
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sportmonks.Net.Api;
using Sportmonks.Net.Model;
using Sportmonks.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sportmonks.Net.Test.Model
{
    /// <summary>
    ///  Class for testing SportStandingsBySeasonIdResponseSubscriptionInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SportStandingsBySeasonIdResponseSubscriptionInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SportStandingsBySeasonIdResponseSubscriptionInner
        //private SportStandingsBySeasonIdResponseSubscriptionInner instance;

        public SportStandingsBySeasonIdResponseSubscriptionInnerTests()
        {
            // TODO uncomment below to create an instance of SportStandingsBySeasonIdResponseSubscriptionInner
            //instance = new SportStandingsBySeasonIdResponseSubscriptionInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SportStandingsBySeasonIdResponseSubscriptionInner
        /// </summary>
        [Fact]
        public void SportStandingsBySeasonIdResponseSubscriptionInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SportStandingsBySeasonIdResponseSubscriptionInner
            //Assert.IsType<SportStandingsBySeasonIdResponseSubscriptionInner>(instance);
        }


        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }
        /// <summary>
        /// Test the property 'Plans'
        /// </summary>
        [Fact]
        public void PlansTest()
        {
            // TODO unit test for the property 'Plans'
        }
        /// <summary>
        /// Test the property 'AddOns'
        /// </summary>
        [Fact]
        public void AddOnsTest()
        {
            // TODO unit test for the property 'AddOns'
        }
        /// <summary>
        /// Test the property 'Widgets'
        /// </summary>
        [Fact]
        public void WidgetsTest()
        {
            // TODO unit test for the property 'Widgets'
        }

    }

}
