/*
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sportmonks.Net.Api;
using Sportmonks.Net.Model;
using Sportmonks.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sportmonks.Net.Test.Model
{
    /// <summary>
    ///  Class for testing SportTransfersLatestResponseDataInnerDetailedPositionId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SportTransfersLatestResponseDataInnerDetailedPositionIdTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SportTransfersLatestResponseDataInnerDetailedPositionId
        //private SportTransfersLatestResponseDataInnerDetailedPositionId instance;

        public SportTransfersLatestResponseDataInnerDetailedPositionIdTests()
        {
            // TODO uncomment below to create an instance of SportTransfersLatestResponseDataInnerDetailedPositionId
            //instance = new SportTransfersLatestResponseDataInnerDetailedPositionId();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SportTransfersLatestResponseDataInnerDetailedPositionId
        /// </summary>
        [Fact]
        public void SportTransfersLatestResponseDataInnerDetailedPositionIdInstanceTest()
        {
            // TODO uncomment below to test "IsType" SportTransfersLatestResponseDataInnerDetailedPositionId
            //Assert.IsType<SportTransfersLatestResponseDataInnerDetailedPositionId>(instance);
        }



    }

}
