/*
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sportmonks.Net.Api;
using Sportmonks.Net.Model;
using Sportmonks.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sportmonks.Net.Test.Model
{
    /// <summary>
    ///  Class for testing SportSeasonByIdResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SportSeasonByIdResponseDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SportSeasonByIdResponseData
        //private SportSeasonByIdResponseData instance;

        public SportSeasonByIdResponseDataTests()
        {
            // TODO uncomment below to create an instance of SportSeasonByIdResponseData
            //instance = new SportSeasonByIdResponseData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SportSeasonByIdResponseData
        /// </summary>
        [Fact]
        public void SportSeasonByIdResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" SportSeasonByIdResponseData
            //Assert.IsType<SportSeasonByIdResponseData>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'SportId'
        /// </summary>
        [Fact]
        public void SportIdTest()
        {
            // TODO unit test for the property 'SportId'
        }
        /// <summary>
        /// Test the property 'LeagueId'
        /// </summary>
        [Fact]
        public void LeagueIdTest()
        {
            // TODO unit test for the property 'LeagueId'
        }
        /// <summary>
        /// Test the property 'TieBreakerRuleId'
        /// </summary>
        [Fact]
        public void TieBreakerRuleIdTest()
        {
            // TODO unit test for the property 'TieBreakerRuleId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Finished'
        /// </summary>
        [Fact]
        public void FinishedTest()
        {
            // TODO unit test for the property 'Finished'
        }
        /// <summary>
        /// Test the property 'Pending'
        /// </summary>
        [Fact]
        public void PendingTest()
        {
            // TODO unit test for the property 'Pending'
        }
        /// <summary>
        /// Test the property 'IsCurrent'
        /// </summary>
        [Fact]
        public void IsCurrentTest()
        {
            // TODO unit test for the property 'IsCurrent'
        }
        /// <summary>
        /// Test the property 'StartingAt'
        /// </summary>
        [Fact]
        public void StartingAtTest()
        {
            // TODO unit test for the property 'StartingAt'
        }
        /// <summary>
        /// Test the property 'EndingAt'
        /// </summary>
        [Fact]
        public void EndingAtTest()
        {
            // TODO unit test for the property 'EndingAt'
        }
        /// <summary>
        /// Test the property 'StandingsRecalculatedAt'
        /// </summary>
        [Fact]
        public void StandingsRecalculatedAtTest()
        {
            // TODO unit test for the property 'StandingsRecalculatedAt'
        }

    }

}
