/*
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sportmonks.Net.Api;
using Sportmonks.Net.Model;
using Sportmonks.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sportmonks.Net.Test.Model
{
    /// <summary>
    ///  Class for testing SportSquadsByTeamIdResponseSubscriptionInnerPlansInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SportSquadsByTeamIdResponseSubscriptionInnerPlansInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SportSquadsByTeamIdResponseSubscriptionInnerPlansInner
        //private SportSquadsByTeamIdResponseSubscriptionInnerPlansInner instance;

        public SportSquadsByTeamIdResponseSubscriptionInnerPlansInnerTests()
        {
            // TODO uncomment below to create an instance of SportSquadsByTeamIdResponseSubscriptionInnerPlansInner
            //instance = new SportSquadsByTeamIdResponseSubscriptionInnerPlansInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SportSquadsByTeamIdResponseSubscriptionInnerPlansInner
        /// </summary>
        [Fact]
        public void SportSquadsByTeamIdResponseSubscriptionInnerPlansInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SportSquadsByTeamIdResponseSubscriptionInnerPlansInner
            //Assert.IsType<SportSquadsByTeamIdResponseSubscriptionInnerPlansInner>(instance);
        }


        /// <summary>
        /// Test the property 'Plan'
        /// </summary>
        [Fact]
        public void PlanTest()
        {
            // TODO unit test for the property 'Plan'
        }
        /// <summary>
        /// Test the property 'Sport'
        /// </summary>
        [Fact]
        public void SportTest()
        {
            // TODO unit test for the property 'Sport'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }

    }

}
