/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface CitiesAllResponseDataInner
 */
export interface CitiesAllResponseDataInner {
    /**
     * 
     * @type {number}
     * @memberof CitiesAllResponseDataInner
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof CitiesAllResponseDataInner
     */
    'country_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof CitiesAllResponseDataInner
     */
    'region_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CitiesAllResponseDataInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CitiesAllResponseDataInner
     */
    'latitude'?: string;
    /**
     * 
     * @type {string}
     * @memberof CitiesAllResponseDataInner
     */
    'longitude'?: string;
}

