/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { CountriesAllResponseDataInner } from './countries-all-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { CountriesAllResponsePagination } from './countries-all-response-pagination';
// May contain unused imports in some cases
// @ts-ignore
import { CountriesAllResponseRateLimit } from './countries-all-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { CountriesAllResponseSubscriptionInner } from './countries-all-response-subscription-inner';

/**
 * 
 * @export
 * @interface CountriesAllResponse
 */
export interface CountriesAllResponse {
    /**
     * 
     * @type {Array<CountriesAllResponseDataInner>}
     * @memberof CountriesAllResponse
     */
    'data'?: Array<CountriesAllResponseDataInner>;
    /**
     * 
     * @type {CountriesAllResponsePagination}
     * @memberof CountriesAllResponse
     */
    'pagination'?: CountriesAllResponsePagination;
    /**
     * 
     * @type {Array<CountriesAllResponseSubscriptionInner>}
     * @memberof CountriesAllResponse
     */
    'subscription'?: Array<CountriesAllResponseSubscriptionInner>;
    /**
     * 
     * @type {CountriesAllResponseRateLimit}
     * @memberof CountriesAllResponse
     */
    'rate_limit'?: CountriesAllResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof CountriesAllResponse
     */
    'timezone'?: string;
}

