/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface OddsMarketByIdResponseData
 */
export interface OddsMarketByIdResponseData {
    /**
     * 
     * @type {number}
     * @memberof OddsMarketByIdResponseData
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof OddsMarketByIdResponseData
     */
    'legacy_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof OddsMarketByIdResponseData
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof OddsMarketByIdResponseData
     */
    'developer_name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OddsMarketByIdResponseData
     */
    'has_winning_calculations'?: boolean;
}

