/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface OddsBookmakersMappingByFixtureIdResponseDataInner
 */
export interface OddsBookmakersMappingByFixtureIdResponseDataInner {
    /**
     * 
     * @type {number}
     * @memberof OddsBookmakersMappingByFixtureIdResponseDataInner
     */
    'fixture_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof OddsBookmakersMappingByFixtureIdResponseDataInner
     */
    'bookmaker_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof OddsBookmakersMappingByFixtureIdResponseDataInner
     */
    'bookmaker_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof OddsBookmakersMappingByFixtureIdResponseDataInner
     */
    'bookmaker_event_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OddsBookmakersMappingByFixtureIdResponseDataInner
     */
    'bookmaker_event_url'?: string | null;
}

