/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { RegionsAllResponseDataInner } from './regions-all-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { RegionsAllResponsePagination } from './regions-all-response-pagination';
// May contain unused imports in some cases
// @ts-ignore
import { RegionsAllResponseRateLimit } from './regions-all-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { RegionsAllResponseSubscriptionInner } from './regions-all-response-subscription-inner';

/**
 * 
 * @export
 * @interface RegionsAllResponse
 */
export interface RegionsAllResponse {
    /**
     * 
     * @type {Array<RegionsAllResponseDataInner>}
     * @memberof RegionsAllResponse
     */
    'data'?: Array<RegionsAllResponseDataInner>;
    /**
     * 
     * @type {RegionsAllResponsePagination}
     * @memberof RegionsAllResponse
     */
    'pagination'?: RegionsAllResponsePagination;
    /**
     * 
     * @type {Array<RegionsAllResponseSubscriptionInner>}
     * @memberof RegionsAllResponse
     */
    'subscription'?: Array<RegionsAllResponseSubscriptionInner>;
    /**
     * 
     * @type {RegionsAllResponseRateLimit}
     * @memberof RegionsAllResponse
     */
    'rate_limit'?: RegionsAllResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof RegionsAllResponse
     */
    'timezone'?: string;
}

