/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { RegionsSearchResponseDataInner } from './regions-search-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { RegionsSearchResponsePagination } from './regions-search-response-pagination';
// May contain unused imports in some cases
// @ts-ignore
import { RegionsSearchResponseRateLimit } from './regions-search-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { RegionsSearchResponseSubscriptionInner } from './regions-search-response-subscription-inner';

/**
 * 
 * @export
 * @interface RegionsSearchResponse
 */
export interface RegionsSearchResponse {
    /**
     * 
     * @type {Array<RegionsSearchResponseDataInner>}
     * @memberof RegionsSearchResponse
     */
    'data'?: Array<RegionsSearchResponseDataInner>;
    /**
     * 
     * @type {RegionsSearchResponsePagination}
     * @memberof RegionsSearchResponse
     */
    'pagination'?: RegionsSearchResponsePagination;
    /**
     * 
     * @type {Array<RegionsSearchResponseSubscriptionInner>}
     * @memberof RegionsSearchResponse
     */
    'subscription'?: Array<RegionsSearchResponseSubscriptionInner>;
    /**
     * 
     * @type {RegionsSearchResponseRateLimit}
     * @memberof RegionsSearchResponse
     */
    'rate_limit'?: RegionsSearchResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof RegionsSearchResponse
     */
    'timezone'?: string;
}

