/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface SportSeasonsSearchResponseDataInner
 */
export interface SportSeasonsSearchResponseDataInner {
    /**
     * 
     * @type {number}
     * @memberof SportSeasonsSearchResponseDataInner
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportSeasonsSearchResponseDataInner
     */
    'sport_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportSeasonsSearchResponseDataInner
     */
    'league_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportSeasonsSearchResponseDataInner
     */
    'tie_breaker_rule_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SportSeasonsSearchResponseDataInner
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SportSeasonsSearchResponseDataInner
     */
    'finished'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SportSeasonsSearchResponseDataInner
     */
    'pending'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SportSeasonsSearchResponseDataInner
     */
    'is_current'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SportSeasonsSearchResponseDataInner
     */
    'starting_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportSeasonsSearchResponseDataInner
     */
    'ending_at'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SportSeasonsSearchResponseDataInner
     */
    'standings_recalculated_at'?: string;
}

