/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportOddsPreMatchByFixtureAndBookmakerIdResponseSubscriptionInnerPlansInner } from './sport-odds-pre-match-by-fixture-and-bookmaker-id-response-subscription-inner-plans-inner';

/**
 * 
 * @export
 * @interface SportOddsPreMatchByFixtureAndBookmakerIdResponseSubscriptionInner
 */
export interface SportOddsPreMatchByFixtureAndBookmakerIdResponseSubscriptionInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof SportOddsPreMatchByFixtureAndBookmakerIdResponseSubscriptionInner
     */
    'meta'?: Array<string>;
    /**
     * 
     * @type {Array<SportOddsPreMatchByFixtureAndBookmakerIdResponseSubscriptionInnerPlansInner>}
     * @memberof SportOddsPreMatchByFixtureAndBookmakerIdResponseSubscriptionInner
     */
    'plans'?: Array<SportOddsPreMatchByFixtureAndBookmakerIdResponseSubscriptionInnerPlansInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SportOddsPreMatchByFixtureAndBookmakerIdResponseSubscriptionInner
     */
    'add_ons'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SportOddsPreMatchByFixtureAndBookmakerIdResponseSubscriptionInner
     */
    'widgets'?: Array<string>;
}

