/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportFixturesSearchResponseDataInner } from './sport-fixtures-search-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SportFixturesSearchResponsePagination } from './sport-fixtures-search-response-pagination';
// May contain unused imports in some cases
// @ts-ignore
import { SportFixturesSearchResponseRateLimit } from './sport-fixtures-search-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportFixturesSearchResponseSubscriptionInner } from './sport-fixtures-search-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportFixturesSearchResponse
 */
export interface SportFixturesSearchResponse {
    /**
     * 
     * @type {Array<SportFixturesSearchResponseDataInner>}
     * @memberof SportFixturesSearchResponse
     */
    'data'?: Array<SportFixturesSearchResponseDataInner>;
    /**
     * 
     * @type {SportFixturesSearchResponsePagination}
     * @memberof SportFixturesSearchResponse
     */
    'pagination'?: SportFixturesSearchResponsePagination;
    /**
     * 
     * @type {Array<SportFixturesSearchResponseSubscriptionInner>}
     * @memberof SportFixturesSearchResponse
     */
    'subscription'?: Array<SportFixturesSearchResponseSubscriptionInner>;
    /**
     * 
     * @type {SportFixturesSearchResponseRateLimit}
     * @memberof SportFixturesSearchResponse
     */
    'rate_limit'?: SportFixturesSearchResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportFixturesSearchResponse
     */
    'timezone'?: string;
}

