/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportStandingsAllResponseDataInner } from './sport-standings-all-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SportStandingsAllResponsePagination } from './sport-standings-all-response-pagination';
// May contain unused imports in some cases
// @ts-ignore
import { SportStandingsAllResponseRateLimit } from './sport-standings-all-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportStandingsAllResponseSubscriptionInner } from './sport-standings-all-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportStandingsAllResponse
 */
export interface SportStandingsAllResponse {
    /**
     * 
     * @type {Array<SportStandingsAllResponseDataInner>}
     * @memberof SportStandingsAllResponse
     */
    'data'?: Array<SportStandingsAllResponseDataInner>;
    /**
     * 
     * @type {SportStandingsAllResponsePagination}
     * @memberof SportStandingsAllResponse
     */
    'pagination'?: SportStandingsAllResponsePagination;
    /**
     * 
     * @type {Array<SportStandingsAllResponseSubscriptionInner>}
     * @memberof SportStandingsAllResponse
     */
    'subscription'?: Array<SportStandingsAllResponseSubscriptionInner>;
    /**
     * 
     * @type {SportStandingsAllResponseRateLimit}
     * @memberof SportStandingsAllResponse
     */
    'rate_limit'?: SportStandingsAllResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportStandingsAllResponse
     */
    'timezone'?: string;
}

