/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportStateByIdResponseData } from './sport-state-by-id-response-data';
// May contain unused imports in some cases
// @ts-ignore
import { SportStateByIdResponseRateLimit } from './sport-state-by-id-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportStateByIdResponseSubscriptionInner } from './sport-state-by-id-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportStateByIdResponse
 */
export interface SportStateByIdResponse {
    /**
     * 
     * @type {SportStateByIdResponseData}
     * @memberof SportStateByIdResponse
     */
    'data'?: SportStateByIdResponseData;
    /**
     * 
     * @type {Array<SportStateByIdResponseSubscriptionInner>}
     * @memberof SportStateByIdResponse
     */
    'subscription'?: Array<SportStateByIdResponseSubscriptionInner>;
    /**
     * 
     * @type {SportStateByIdResponseRateLimit}
     * @memberof SportStateByIdResponse
     */
    'rate_limit'?: SportStateByIdResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportStateByIdResponse
     */
    'timezone'?: string;
}

