/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface SportNewsPreMatchBySeasonIdResponseSubscriptionInnerPlansInner
 */
export interface SportNewsPreMatchBySeasonIdResponseSubscriptionInnerPlansInner {
    /**
     * 
     * @type {string}
     * @memberof SportNewsPreMatchBySeasonIdResponseSubscriptionInnerPlansInner
     */
    'plan'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportNewsPreMatchBySeasonIdResponseSubscriptionInnerPlansInner
     */
    'sport'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportNewsPreMatchBySeasonIdResponseSubscriptionInnerPlansInner
     */
    'category'?: string;
}

