/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportVenuesBySeasonIdResponseDataInner } from './sport-venues-by-season-id-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SportVenuesBySeasonIdResponseRateLimit } from './sport-venues-by-season-id-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportVenuesBySeasonIdResponseSubscriptionInner } from './sport-venues-by-season-id-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportVenuesBySeasonIdResponse
 */
export interface SportVenuesBySeasonIdResponse {
    /**
     * 
     * @type {Array<SportVenuesBySeasonIdResponseDataInner>}
     * @memberof SportVenuesBySeasonIdResponse
     */
    'data'?: Array<SportVenuesBySeasonIdResponseDataInner>;
    /**
     * 
     * @type {Array<SportVenuesBySeasonIdResponseSubscriptionInner>}
     * @memberof SportVenuesBySeasonIdResponse
     */
    'subscription'?: Array<SportVenuesBySeasonIdResponseSubscriptionInner>;
    /**
     * 
     * @type {SportVenuesBySeasonIdResponseRateLimit}
     * @memberof SportVenuesBySeasonIdResponse
     */
    'rate_limit'?: SportVenuesBySeasonIdResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportVenuesBySeasonIdResponse
     */
    'timezone'?: string;
}

