/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportSeasonByIdResponseSubscriptionInnerPlansInner } from './sport-season-by-id-response-subscription-inner-plans-inner';

/**
 * 
 * @export
 * @interface SportSeasonByIdResponseSubscriptionInner
 */
export interface SportSeasonByIdResponseSubscriptionInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof SportSeasonByIdResponseSubscriptionInner
     */
    'meta'?: Array<string>;
    /**
     * 
     * @type {Array<SportSeasonByIdResponseSubscriptionInnerPlansInner>}
     * @memberof SportSeasonByIdResponseSubscriptionInner
     */
    'plans'?: Array<SportSeasonByIdResponseSubscriptionInnerPlansInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SportSeasonByIdResponseSubscriptionInner
     */
    'add_ons'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SportSeasonByIdResponseSubscriptionInner
     */
    'widgets'?: Array<string>;
}

