/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportLeaguesByDateResponseSubscriptionInnerPlansInner } from './sport-leagues-by-date-response-subscription-inner-plans-inner';

/**
 * 
 * @export
 * @interface SportLeaguesByDateResponseSubscriptionInner
 */
export interface SportLeaguesByDateResponseSubscriptionInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof SportLeaguesByDateResponseSubscriptionInner
     */
    'meta'?: Array<string>;
    /**
     * 
     * @type {Array<SportLeaguesByDateResponseSubscriptionInnerPlansInner>}
     * @memberof SportLeaguesByDateResponseSubscriptionInner
     */
    'plans'?: Array<SportLeaguesByDateResponseSubscriptionInnerPlansInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SportLeaguesByDateResponseSubscriptionInner
     */
    'add_ons'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SportLeaguesByDateResponseSubscriptionInner
     */
    'widgets'?: Array<string>;
}

