/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportStatesBySportResponseDataInner } from './sport-states-by-sport-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SportStatesBySportResponsePagination } from './sport-states-by-sport-response-pagination';
// May contain unused imports in some cases
// @ts-ignore
import { SportStatesBySportResponseRateLimit } from './sport-states-by-sport-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportStatesBySportResponseSubscriptionInner } from './sport-states-by-sport-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportStatesBySportResponse
 */
export interface SportStatesBySportResponse {
    /**
     * 
     * @type {Array<SportStatesBySportResponseDataInner>}
     * @memberof SportStatesBySportResponse
     */
    'data'?: Array<SportStatesBySportResponseDataInner>;
    /**
     * 
     * @type {SportStatesBySportResponsePagination}
     * @memberof SportStatesBySportResponse
     */
    'pagination'?: SportStatesBySportResponsePagination;
    /**
     * 
     * @type {Array<SportStatesBySportResponseSubscriptionInner>}
     * @memberof SportStatesBySportResponse
     */
    'subscription'?: Array<SportStatesBySportResponseSubscriptionInner>;
    /**
     * 
     * @type {SportStatesBySportResponseRateLimit}
     * @memberof SportStatesBySportResponse
     */
    'rate_limit'?: SportStatesBySportResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportStatesBySportResponse
     */
    'timezone'?: string;
}

