/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportFixturesByDateRangeResponseSubscriptionInnerPlansInner } from './sport-fixtures-by-date-range-response-subscription-inner-plans-inner';

/**
 * 
 * @export
 * @interface SportFixturesByDateRangeResponseSubscriptionInner
 */
export interface SportFixturesByDateRangeResponseSubscriptionInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof SportFixturesByDateRangeResponseSubscriptionInner
     */
    'meta'?: Array<string>;
    /**
     * 
     * @type {Array<SportFixturesByDateRangeResponseSubscriptionInnerPlansInner>}
     * @memberof SportFixturesByDateRangeResponseSubscriptionInner
     */
    'plans'?: Array<SportFixturesByDateRangeResponseSubscriptionInnerPlansInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SportFixturesByDateRangeResponseSubscriptionInner
     */
    'add_ons'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SportFixturesByDateRangeResponseSubscriptionInner
     */
    'widgets'?: Array<string>;
}

