/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface SportCommentariesAllResponseRateLimit
 */
export interface SportCommentariesAllResponseRateLimit {
    /**
     * 
     * @type {number}
     * @memberof SportCommentariesAllResponseRateLimit
     */
    'resets_in_seconds'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportCommentariesAllResponseRateLimit
     */
    'remaining'?: number;
    /**
     * 
     * @type {string}
     * @memberof SportCommentariesAllResponseRateLimit
     */
    'requested_entity'?: string;
}

