/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportTransfersAllResponseSubscriptionInnerPlansInner } from './sport-transfers-all-response-subscription-inner-plans-inner';

/**
 * 
 * @export
 * @interface SportTransfersAllResponseSubscriptionInner
 */
export interface SportTransfersAllResponseSubscriptionInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof SportTransfersAllResponseSubscriptionInner
     */
    'meta'?: Array<string>;
    /**
     * 
     * @type {Array<SportTransfersAllResponseSubscriptionInnerPlansInner>}
     * @memberof SportTransfersAllResponseSubscriptionInner
     */
    'plans'?: Array<SportTransfersAllResponseSubscriptionInnerPlansInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SportTransfersAllResponseSubscriptionInner
     */
    'add_ons'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SportTransfersAllResponseSubscriptionInner
     */
    'widgets'?: Array<string>;
}

