/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportSquadsBySeasonAndTeamIdResponseRateLimit } from './sport-squads-by-season-and-team-id-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportSquadsBySeasonAndTeamIdResponseSubscriptionInner } from './sport-squads-by-season-and-team-id-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportSquadsBySeasonAndTeamIdResponse
 */
export interface SportSquadsBySeasonAndTeamIdResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof SportSquadsBySeasonAndTeamIdResponse
     */
    'data'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SportSquadsBySeasonAndTeamIdResponse
     */
    'message'?: string;
    /**
     * 
     * @type {Array<SportSquadsBySeasonAndTeamIdResponseSubscriptionInner>}
     * @memberof SportSquadsBySeasonAndTeamIdResponse
     */
    'subscription'?: Array<SportSquadsBySeasonAndTeamIdResponseSubscriptionInner>;
    /**
     * 
     * @type {SportSquadsBySeasonAndTeamIdResponseRateLimit}
     * @memberof SportSquadsBySeasonAndTeamIdResponse
     */
    'rate_limit'?: SportSquadsBySeasonAndTeamIdResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportSquadsBySeasonAndTeamIdResponse
     */
    'timezone'?: string;
}

