/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface SportSchedulesByTeamAndSeasonIdResponseDataInnerRoundsInner
 */
export interface SportSchedulesByTeamAndSeasonIdResponseDataInnerRoundsInner {
    /**
     * 
     * @type {number}
     * @memberof SportSchedulesByTeamAndSeasonIdResponseDataInnerRoundsInner
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportSchedulesByTeamAndSeasonIdResponseDataInnerRoundsInner
     */
    'sport_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportSchedulesByTeamAndSeasonIdResponseDataInnerRoundsInner
     */
    'league_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportSchedulesByTeamAndSeasonIdResponseDataInnerRoundsInner
     */
    'season_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportSchedulesByTeamAndSeasonIdResponseDataInnerRoundsInner
     */
    'stage_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SportSchedulesByTeamAndSeasonIdResponseDataInnerRoundsInner
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SportSchedulesByTeamAndSeasonIdResponseDataInnerRoundsInner
     */
    'finished'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SportSchedulesByTeamAndSeasonIdResponseDataInnerRoundsInner
     */
    'is_current'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SportSchedulesByTeamAndSeasonIdResponseDataInnerRoundsInner
     */
    'starting_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportSchedulesByTeamAndSeasonIdResponseDataInnerRoundsInner
     */
    'ending_at'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SportSchedulesByTeamAndSeasonIdResponseDataInnerRoundsInner
     */
    'fixtures'?: Array<string>;
}

