/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportTvStationByIdResponseSubscriptionInnerPlansInner } from './sport-tv-station-by-id-response-subscription-inner-plans-inner';

/**
 * 
 * @export
 * @interface SportTvStationByIdResponseSubscriptionInner
 */
export interface SportTvStationByIdResponseSubscriptionInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof SportTvStationByIdResponseSubscriptionInner
     */
    'meta'?: Array<string>;
    /**
     * 
     * @type {Array<SportTvStationByIdResponseSubscriptionInnerPlansInner>}
     * @memberof SportTvStationByIdResponseSubscriptionInner
     */
    'plans'?: Array<SportTvStationByIdResponseSubscriptionInnerPlansInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SportTvStationByIdResponseSubscriptionInner
     */
    'add_ons'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SportTvStationByIdResponseSubscriptionInner
     */
    'widgets'?: Array<string>;
}

