/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportOddsInPlayByFixtureIdResponseSubscriptionInnerAddOnsInner } from './sport-odds-in-play-by-fixture-id-response-subscription-inner-add-ons-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SportOddsInPlayByFixtureIdResponseSubscriptionInnerPlansInner } from './sport-odds-in-play-by-fixture-id-response-subscription-inner-plans-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SportStandingsLiveByLeagueIdResponseSubscriptionInnerMeta } from './sport-standings-live-by-league-id-response-subscription-inner-meta';

/**
 * 
 * @export
 * @interface SportOddsInPlayByFixtureIdResponseSubscriptionInner
 */
export interface SportOddsInPlayByFixtureIdResponseSubscriptionInner {
    /**
     * 
     * @type {SportStandingsLiveByLeagueIdResponseSubscriptionInnerMeta}
     * @memberof SportOddsInPlayByFixtureIdResponseSubscriptionInner
     */
    'meta'?: SportStandingsLiveByLeagueIdResponseSubscriptionInnerMeta;
    /**
     * 
     * @type {Array<SportOddsInPlayByFixtureIdResponseSubscriptionInnerPlansInner>}
     * @memberof SportOddsInPlayByFixtureIdResponseSubscriptionInner
     */
    'plans'?: Array<SportOddsInPlayByFixtureIdResponseSubscriptionInnerPlansInner>;
    /**
     * 
     * @type {Array<SportOddsInPlayByFixtureIdResponseSubscriptionInnerAddOnsInner>}
     * @memberof SportOddsInPlayByFixtureIdResponseSubscriptionInner
     */
    'add_ons'?: Array<SportOddsInPlayByFixtureIdResponseSubscriptionInnerAddOnsInner>;
}

