/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportTeamsAllResponseDataInner } from './sport-teams-all-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SportTeamsAllResponsePagination } from './sport-teams-all-response-pagination';
// May contain unused imports in some cases
// @ts-ignore
import { SportTeamsAllResponseRateLimit } from './sport-teams-all-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportTeamsAllResponseSubscriptionInner } from './sport-teams-all-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportTeamsAllResponse
 */
export interface SportTeamsAllResponse {
    /**
     * 
     * @type {Array<SportTeamsAllResponseDataInner>}
     * @memberof SportTeamsAllResponse
     */
    'data'?: Array<SportTeamsAllResponseDataInner>;
    /**
     * 
     * @type {SportTeamsAllResponsePagination}
     * @memberof SportTeamsAllResponse
     */
    'pagination'?: SportTeamsAllResponsePagination;
    /**
     * 
     * @type {Array<SportTeamsAllResponseSubscriptionInner>}
     * @memberof SportTeamsAllResponse
     */
    'subscription'?: Array<SportTeamsAllResponseSubscriptionInner>;
    /**
     * 
     * @type {SportTeamsAllResponseRateLimit}
     * @memberof SportTeamsAllResponse
     */
    'rate_limit'?: SportTeamsAllResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportTeamsAllResponse
     */
    'timezone'?: string;
}

