/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportNewsPreMatchBySeasonIdResponseDataInner } from './sport-news-pre-match-by-season-id-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SportNewsPreMatchBySeasonIdResponsePagination } from './sport-news-pre-match-by-season-id-response-pagination';
// May contain unused imports in some cases
// @ts-ignore
import { SportNewsPreMatchBySeasonIdResponseRateLimit } from './sport-news-pre-match-by-season-id-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportNewsPreMatchBySeasonIdResponseSubscriptionInner } from './sport-news-pre-match-by-season-id-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportNewsPreMatchBySeasonIdResponse
 */
export interface SportNewsPreMatchBySeasonIdResponse {
    /**
     * 
     * @type {Array<SportNewsPreMatchBySeasonIdResponseDataInner>}
     * @memberof SportNewsPreMatchBySeasonIdResponse
     */
    'data'?: Array<SportNewsPreMatchBySeasonIdResponseDataInner>;
    /**
     * 
     * @type {SportNewsPreMatchBySeasonIdResponsePagination}
     * @memberof SportNewsPreMatchBySeasonIdResponse
     */
    'pagination'?: SportNewsPreMatchBySeasonIdResponsePagination;
    /**
     * 
     * @type {Array<SportNewsPreMatchBySeasonIdResponseSubscriptionInner>}
     * @memberof SportNewsPreMatchBySeasonIdResponse
     */
    'subscription'?: Array<SportNewsPreMatchBySeasonIdResponseSubscriptionInner>;
    /**
     * 
     * @type {SportNewsPreMatchBySeasonIdResponseRateLimit}
     * @memberof SportNewsPreMatchBySeasonIdResponse
     */
    'rate_limit'?: SportNewsPreMatchBySeasonIdResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportNewsPreMatchBySeasonIdResponse
     */
    'timezone'?: string;
}

