/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface SportTransferByIdResponseData
 */
export interface SportTransferByIdResponseData {
    /**
     * 
     * @type {number}
     * @memberof SportTransferByIdResponseData
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportTransferByIdResponseData
     */
    'sport_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportTransferByIdResponseData
     */
    'player_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportTransferByIdResponseData
     */
    'type_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportTransferByIdResponseData
     */
    'from_team_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportTransferByIdResponseData
     */
    'to_team_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportTransferByIdResponseData
     */
    'position_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportTransferByIdResponseData
     */
    'detailed_position_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SportTransferByIdResponseData
     */
    'date'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SportTransferByIdResponseData
     */
    'career_ended'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SportTransferByIdResponseData
     */
    'completed'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SportTransferByIdResponseData
     */
    'completed_at'?: string;
}

