/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportCommentariesByFixtureIdResponseRateLimit } from './sport-commentaries-by-fixture-id-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportCommentariesByFixtureIdResponseSubscriptionInner } from './sport-commentaries-by-fixture-id-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportCommentariesByFixtureIdResponse
 */
export interface SportCommentariesByFixtureIdResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof SportCommentariesByFixtureIdResponse
     */
    'data'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SportCommentariesByFixtureIdResponse
     */
    'message'?: string;
    /**
     * 
     * @type {Array<SportCommentariesByFixtureIdResponseSubscriptionInner>}
     * @memberof SportCommentariesByFixtureIdResponse
     */
    'subscription'?: Array<SportCommentariesByFixtureIdResponseSubscriptionInner>;
    /**
     * 
     * @type {SportCommentariesByFixtureIdResponseRateLimit}
     * @memberof SportCommentariesByFixtureIdResponse
     */
    'rate_limit'?: SportCommentariesByFixtureIdResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportCommentariesByFixtureIdResponse
     */
    'timezone'?: string;
}

