/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportFixturesSearchResponseSubscriptionInnerPlansInner } from './sport-fixtures-search-response-subscription-inner-plans-inner';

/**
 * 
 * @export
 * @interface SportFixturesSearchResponseSubscriptionInner
 */
export interface SportFixturesSearchResponseSubscriptionInner {
    /**
     * 
     * @type {Array<string>}
     * @memberof SportFixturesSearchResponseSubscriptionInner
     */
    'meta'?: Array<string>;
    /**
     * 
     * @type {Array<SportFixturesSearchResponseSubscriptionInnerPlansInner>}
     * @memberof SportFixturesSearchResponseSubscriptionInner
     */
    'plans'?: Array<SportFixturesSearchResponseSubscriptionInnerPlansInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SportFixturesSearchResponseSubscriptionInner
     */
    'add_ons'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SportFixturesSearchResponseSubscriptionInner
     */
    'widgets'?: Array<string>;
}

