/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportVenueByIdResponseData } from './sport-venue-by-id-response-data';
// May contain unused imports in some cases
// @ts-ignore
import { SportVenueByIdResponseRateLimit } from './sport-venue-by-id-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportVenueByIdResponseSubscriptionInner } from './sport-venue-by-id-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportVenueByIdResponse
 */
export interface SportVenueByIdResponse {
    /**
     * 
     * @type {SportVenueByIdResponseData}
     * @memberof SportVenueByIdResponse
     */
    'data'?: SportVenueByIdResponseData;
    /**
     * 
     * @type {Array<SportVenueByIdResponseSubscriptionInner>}
     * @memberof SportVenueByIdResponse
     */
    'subscription'?: Array<SportVenueByIdResponseSubscriptionInner>;
    /**
     * 
     * @type {SportVenueByIdResponseRateLimit}
     * @memberof SportVenueByIdResponse
     */
    'rate_limit'?: SportVenueByIdResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportVenueByIdResponse
     */
    'timezone'?: string;
}

