/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface SportCoachesSearchResponseDataInner
 */
export interface SportCoachesSearchResponseDataInner {
    /**
     * 
     * @type {number}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'player_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'sport_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'country_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'nationality_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'city_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'common_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'firstname'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'lastname'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'display_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'image_path'?: string;
    /**
     * 
     * @type {number}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'height'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'weight'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'date_of_birth'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportCoachesSearchResponseDataInner
     */
    'gender'?: string;
}

