/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportRoundsSearchResponseDataInner } from './sport-rounds-search-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SportRoundsSearchResponsePagination } from './sport-rounds-search-response-pagination';
// May contain unused imports in some cases
// @ts-ignore
import { SportRoundsSearchResponseRateLimit } from './sport-rounds-search-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportRoundsSearchResponseSubscriptionInner } from './sport-rounds-search-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportRoundsSearchResponse
 */
export interface SportRoundsSearchResponse {
    /**
     * 
     * @type {Array<SportRoundsSearchResponseDataInner>}
     * @memberof SportRoundsSearchResponse
     */
    'data'?: Array<SportRoundsSearchResponseDataInner>;
    /**
     * 
     * @type {SportRoundsSearchResponsePagination}
     * @memberof SportRoundsSearchResponse
     */
    'pagination'?: SportRoundsSearchResponsePagination;
    /**
     * 
     * @type {Array<SportRoundsSearchResponseSubscriptionInner>}
     * @memberof SportRoundsSearchResponse
     */
    'subscription'?: Array<SportRoundsSearchResponseSubscriptionInner>;
    /**
     * 
     * @type {SportRoundsSearchResponseRateLimit}
     * @memberof SportRoundsSearchResponse
     */
    'rate_limit'?: SportRoundsSearchResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportRoundsSearchResponse
     */
    'timezone'?: string;
}

