/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportFixturesByIdsResponseDataInner } from './sport-fixtures-by-ids-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SportFixturesByIdsResponseRateLimit } from './sport-fixtures-by-ids-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportFixturesByIdsResponseSubscriptionInner } from './sport-fixtures-by-ids-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportFixturesByIdsResponse
 */
export interface SportFixturesByIdsResponse {
    /**
     * 
     * @type {Array<SportFixturesByIdsResponseDataInner>}
     * @memberof SportFixturesByIdsResponse
     */
    'data'?: Array<SportFixturesByIdsResponseDataInner>;
    /**
     * 
     * @type {Array<SportFixturesByIdsResponseSubscriptionInner>}
     * @memberof SportFixturesByIdsResponse
     */
    'subscription'?: Array<SportFixturesByIdsResponseSubscriptionInner>;
    /**
     * 
     * @type {SportFixturesByIdsResponseRateLimit}
     * @memberof SportFixturesByIdsResponse
     */
    'rate_limit'?: SportFixturesByIdsResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportFixturesByIdsResponse
     */
    'timezone'?: string;
}

