/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportTeamsBySeasonIdResponseDataInner } from './sport-teams-by-season-id-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SportTeamsBySeasonIdResponseRateLimit } from './sport-teams-by-season-id-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportTeamsBySeasonIdResponseSubscriptionInner } from './sport-teams-by-season-id-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportTeamsBySeasonIdResponse
 */
export interface SportTeamsBySeasonIdResponse {
    /**
     * 
     * @type {Array<SportTeamsBySeasonIdResponseDataInner>}
     * @memberof SportTeamsBySeasonIdResponse
     */
    'data'?: Array<SportTeamsBySeasonIdResponseDataInner>;
    /**
     * 
     * @type {Array<SportTeamsBySeasonIdResponseSubscriptionInner>}
     * @memberof SportTeamsBySeasonIdResponse
     */
    'subscription'?: Array<SportTeamsBySeasonIdResponseSubscriptionInner>;
    /**
     * 
     * @type {SportTeamsBySeasonIdResponseRateLimit}
     * @memberof SportTeamsBySeasonIdResponse
     */
    'rate_limit'?: SportTeamsBySeasonIdResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportTeamsBySeasonIdResponse
     */
    'timezone'?: string;
}

