/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportTransfersByPlayerIdResponseDataInner } from './sport-transfers-by-player-id-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SportTransfersByPlayerIdResponsePagination } from './sport-transfers-by-player-id-response-pagination';
// May contain unused imports in some cases
// @ts-ignore
import { SportTransfersByPlayerIdResponseRateLimit } from './sport-transfers-by-player-id-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportTransfersByPlayerIdResponseSubscriptionInner } from './sport-transfers-by-player-id-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportTransfersByPlayerIdResponse
 */
export interface SportTransfersByPlayerIdResponse {
    /**
     * 
     * @type {Array<SportTransfersByPlayerIdResponseDataInner>}
     * @memberof SportTransfersByPlayerIdResponse
     */
    'data'?: Array<SportTransfersByPlayerIdResponseDataInner>;
    /**
     * 
     * @type {SportTransfersByPlayerIdResponsePagination}
     * @memberof SportTransfersByPlayerIdResponse
     */
    'pagination'?: SportTransfersByPlayerIdResponsePagination;
    /**
     * 
     * @type {Array<SportTransfersByPlayerIdResponseSubscriptionInner>}
     * @memberof SportTransfersByPlayerIdResponse
     */
    'subscription'?: Array<SportTransfersByPlayerIdResponseSubscriptionInner>;
    /**
     * 
     * @type {SportTransfersByPlayerIdResponseRateLimit}
     * @memberof SportTransfersByPlayerIdResponse
     */
    'rate_limit'?: SportTransfersByPlayerIdResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportTransfersByPlayerIdResponse
     */
    'timezone'?: string;
}

