/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface SportCommentariesAllResponseDataInner
 */
export interface SportCommentariesAllResponseDataInner {
    /**
     * 
     * @type {number}
     * @memberof SportCommentariesAllResponseDataInner
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportCommentariesAllResponseDataInner
     */
    'fixture_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SportCommentariesAllResponseDataInner
     */
    'player_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SportCommentariesAllResponseDataInner
     */
    'related_player_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SportCommentariesAllResponseDataInner
     */
    'comment'?: string;
    /**
     * 
     * @type {number}
     * @memberof SportCommentariesAllResponseDataInner
     */
    'minute'?: number;
    /**
     * 
     * @type {string}
     * @memberof SportCommentariesAllResponseDataInner
     */
    'extra_minute'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SportCommentariesAllResponseDataInner
     */
    'is_goal'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SportCommentariesAllResponseDataInner
     */
    'is_important'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SportCommentariesAllResponseDataInner
     */
    'order'?: number;
}

