/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface SportTopScorersBySeasonIdResponseDataInner
 */
export interface SportTopScorersBySeasonIdResponseDataInner {
    /**
     * 
     * @type {number}
     * @memberof SportTopScorersBySeasonIdResponseDataInner
     */
    'season_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportTopScorersBySeasonIdResponseDataInner
     */
    'player_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportTopScorersBySeasonIdResponseDataInner
     */
    'type_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportTopScorersBySeasonIdResponseDataInner
     */
    'team_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportTopScorersBySeasonIdResponseDataInner
     */
    'position'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportTopScorersBySeasonIdResponseDataInner
     */
    'total'?: number;
    /**
     * 
     * @type {string}
     * @memberof SportTopScorersBySeasonIdResponseDataInner
     */
    'points'?: string | null;
}

