/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportRefereesByCountryIdResponseDataInner } from './sport-referees-by-country-id-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SportRefereesByCountryIdResponsePagination } from './sport-referees-by-country-id-response-pagination';
// May contain unused imports in some cases
// @ts-ignore
import { SportRefereesByCountryIdResponseRateLimit } from './sport-referees-by-country-id-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportRefereesByCountryIdResponseSubscriptionInner } from './sport-referees-by-country-id-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportRefereesByCountryIdResponse
 */
export interface SportRefereesByCountryIdResponse {
    /**
     * 
     * @type {Array<SportRefereesByCountryIdResponseDataInner>}
     * @memberof SportRefereesByCountryIdResponse
     */
    'data'?: Array<SportRefereesByCountryIdResponseDataInner>;
    /**
     * 
     * @type {SportRefereesByCountryIdResponsePagination}
     * @memberof SportRefereesByCountryIdResponse
     */
    'pagination'?: SportRefereesByCountryIdResponsePagination;
    /**
     * 
     * @type {Array<SportRefereesByCountryIdResponseSubscriptionInner>}
     * @memberof SportRefereesByCountryIdResponse
     */
    'subscription'?: Array<SportRefereesByCountryIdResponseSubscriptionInner>;
    /**
     * 
     * @type {SportRefereesByCountryIdResponseRateLimit}
     * @memberof SportRefereesByCountryIdResponse
     */
    'rate_limit'?: SportRefereesByCountryIdResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportRefereesByCountryIdResponse
     */
    'timezone'?: string;
}

