/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportVenuesSearchResponseDataInner } from './sport-venues-search-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SportVenuesSearchResponsePagination } from './sport-venues-search-response-pagination';
// May contain unused imports in some cases
// @ts-ignore
import { SportVenuesSearchResponseRateLimit } from './sport-venues-search-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportVenuesSearchResponseSubscriptionInner } from './sport-venues-search-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportVenuesSearchResponse
 */
export interface SportVenuesSearchResponse {
    /**
     * 
     * @type {Array<SportVenuesSearchResponseDataInner>}
     * @memberof SportVenuesSearchResponse
     */
    'data'?: Array<SportVenuesSearchResponseDataInner>;
    /**
     * 
     * @type {SportVenuesSearchResponsePagination}
     * @memberof SportVenuesSearchResponse
     */
    'pagination'?: SportVenuesSearchResponsePagination;
    /**
     * 
     * @type {Array<SportVenuesSearchResponseSubscriptionInner>}
     * @memberof SportVenuesSearchResponse
     */
    'subscription'?: Array<SportVenuesSearchResponseSubscriptionInner>;
    /**
     * 
     * @type {SportVenuesSearchResponseRateLimit}
     * @memberof SportVenuesSearchResponse
     */
    'rate_limit'?: SportVenuesSearchResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportVenuesSearchResponse
     */
    'timezone'?: string;
}

