/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportTeamsByIdResponseData } from './sport-teams-by-id-response-data';
// May contain unused imports in some cases
// @ts-ignore
import { SportTeamsByIdResponseRateLimit } from './sport-teams-by-id-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportTeamsByIdResponseSubscriptionInner } from './sport-teams-by-id-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportTeamsByIdResponse
 */
export interface SportTeamsByIdResponse {
    /**
     * 
     * @type {SportTeamsByIdResponseData}
     * @memberof SportTeamsByIdResponse
     */
    'data'?: SportTeamsByIdResponseData;
    /**
     * 
     * @type {Array<SportTeamsByIdResponseSubscriptionInner>}
     * @memberof SportTeamsByIdResponse
     */
    'subscription'?: Array<SportTeamsByIdResponseSubscriptionInner>;
    /**
     * 
     * @type {SportTeamsByIdResponseRateLimit}
     * @memberof SportTeamsByIdResponse
     */
    'rate_limit'?: SportTeamsByIdResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportTeamsByIdResponse
     */
    'timezone'?: string;
}

