/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface SportLeaguesByDateResponseDataInner
 */
export interface SportLeaguesByDateResponseDataInner {
    /**
     * 
     * @type {number}
     * @memberof SportLeaguesByDateResponseDataInner
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportLeaguesByDateResponseDataInner
     */
    'sport_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportLeaguesByDateResponseDataInner
     */
    'country_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SportLeaguesByDateResponseDataInner
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SportLeaguesByDateResponseDataInner
     */
    'active'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SportLeaguesByDateResponseDataInner
     */
    'short_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportLeaguesByDateResponseDataInner
     */
    'image_path'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportLeaguesByDateResponseDataInner
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportLeaguesByDateResponseDataInner
     */
    'sub_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportLeaguesByDateResponseDataInner
     */
    'last_played_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof SportLeaguesByDateResponseDataInner
     */
    'category'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SportLeaguesByDateResponseDataInner
     */
    'has_jerseys'?: boolean;
}

