/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { SportSchedulesByTeamAndSeasonIdResponseDataInner } from './sport-schedules-by-team-and-season-id-response-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SportSchedulesByTeamAndSeasonIdResponseRateLimit } from './sport-schedules-by-team-and-season-id-response-rate-limit';
// May contain unused imports in some cases
// @ts-ignore
import { SportSchedulesByTeamAndSeasonIdResponseSubscriptionInner } from './sport-schedules-by-team-and-season-id-response-subscription-inner';

/**
 * 
 * @export
 * @interface SportSchedulesByTeamAndSeasonIdResponse
 */
export interface SportSchedulesByTeamAndSeasonIdResponse {
    /**
     * 
     * @type {Array<SportSchedulesByTeamAndSeasonIdResponseDataInner>}
     * @memberof SportSchedulesByTeamAndSeasonIdResponse
     */
    'data'?: Array<SportSchedulesByTeamAndSeasonIdResponseDataInner>;
    /**
     * 
     * @type {Array<SportSchedulesByTeamAndSeasonIdResponseSubscriptionInner>}
     * @memberof SportSchedulesByTeamAndSeasonIdResponse
     */
    'subscription'?: Array<SportSchedulesByTeamAndSeasonIdResponseSubscriptionInner>;
    /**
     * 
     * @type {SportSchedulesByTeamAndSeasonIdResponseRateLimit}
     * @memberof SportSchedulesByTeamAndSeasonIdResponse
     */
    'rate_limit'?: SportSchedulesByTeamAndSeasonIdResponseRateLimit;
    /**
     * 
     * @type {string}
     * @memberof SportSchedulesByTeamAndSeasonIdResponse
     */
    'timezone'?: string;
}

