/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface SportNewsUpcomingPreMatchResponsePagination
 */
export interface SportNewsUpcomingPreMatchResponsePagination {
    /**
     * 
     * @type {number}
     * @memberof SportNewsUpcomingPreMatchResponsePagination
     */
    'count'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportNewsUpcomingPreMatchResponsePagination
     */
    'per_page'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportNewsUpcomingPreMatchResponsePagination
     */
    'current_page'?: number;
    /**
     * 
     * @type {string}
     * @memberof SportNewsUpcomingPreMatchResponsePagination
     */
    'next_page'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SportNewsUpcomingPreMatchResponsePagination
     */
    'has_more'?: boolean;
}

