/* tslint:disable */
/* eslint-disable */
/**
 * SportMonks
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface SportOddsInPlayByFixtureIdResponseDataInner
 */
export interface SportOddsInPlayByFixtureIdResponseDataInner {
    /**
     * 
     * @type {number}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'fixture_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'provider_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'external_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'market_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'bookmaker_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'label'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'value'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'name'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'sort_order'?: number;
    /**
     * 
     * @type {string}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'market_description'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'probability'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'dp3'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'fractional'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'american'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'winning'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'suspended'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'stopped'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'total'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'handicap'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'participants'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof SportOddsInPlayByFixtureIdResponseDataInner
     */
    'updated_at'?: string;
}

