# coding: utf-8

"""
    SportMonks

    Surpass the competition with superior sports data

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import sportmonks
from sportmonks.paths.version_odds_bookmakers_bookmaker_id import get
from sportmonks import configuration, schemas, api_client

from .. import ApiTestMixin


class TestVersionOddsBookmakersBookmakerId(ApiTestMixin, unittest.TestCase):
    """
    VersionOddsBookmakersBookmakerId unit test stubs
        By ID
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 0




if __name__ == '__main__':
    unittest.main()
