/*
 * SportMonks
 *
 * Surpass the competition with superior sports data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Sportmonks.Net.Api;

namespace Sportmonks.Net.Client
{
    /// <summary>
    ///  SDK client
    /// </summary>
    public class SportmonksClient
    {
        /// <summary>
        /// API instance
        /// </summary>
        public CitiesApi Cities { get; private set; }

        /// <summary>
        /// API instance
        /// </summary>
        public ContinentsApi Continents { get; private set; }

        /// <summary>
        /// API instance
        /// </summary>
        public CountriesApi Countries { get; private set; }

        /// <summary>
        /// API instance
        /// </summary>
        public MyApi My { get; private set; }

        /// <summary>
        /// API instance
        /// </summary>
        public OddsApi Odds { get; private set; }

        /// <summary>
        /// API instance
        /// </summary>
        public RegionsApi Regions { get; private set; }

        /// <summary>
        /// API instance
        /// </summary>
        public SportApi Sport { get; private set; }

        /// <summary>
        /// API instance
        /// </summary>
        public TypesApi Types { get; private set; }

        /// <summary>
        /// Configuration instance
        /// </summary>
        public readonly Configuration Configuration;

        /// <summary>
        /// Constructor
        /// </summary>
        public SportmonksClient()
        {
            Configuration = new Configuration();
            init();
        }

        private void init()
        {
            Cities = new CitiesApi(Configuration);
            Continents = new ContinentsApi(Configuration);
            Countries = new CountriesApi(Configuration);
            My = new MyApi(Configuration);
            Odds = new OddsApi(Configuration);
            Regions = new RegionsApi(Configuration);
            Sport = new SportApi(Configuration);
            Types = new TypesApi(Configuration);
        }

        /// <summary>
        /// Setter for base path
        /// </summary>
        public SportmonksClient SetBasePath(string basePath)
        {
            Configuration.BasePath = basePath;
            init();
            return this;
        }

        /// <summary>
        /// Setter for Username
        /// </summary>
        public SportmonksClient SetUsername(string username)
        {
            Configuration.Username = username;
            init();
            return this;
        }

        /// <summary>
        /// Setter for Password
        /// </summary>
        public SportmonksClient SetPassword(string password)
        {
            Configuration.Password = password;
            init();
            return this;
        }

        /// <summary>
        /// Setter for Access Token
        /// </summary>
        public SportmonksClient SetAccessToken(string accessToken)
        {
            Configuration.AccessToken = accessToken;
            init();
            return this;
        }

        /// <summary>
        /// Setter for API Key
        /// </summary>
        public SportmonksClient SetApiKey(string apiKey)
        {
            Configuration.ApiKey["Authorization"] = apiKey;
            init();
            return this;
        }

        /// <summary>
        /// Setter for "VersionState" client state
        /// </summary>
        public SportmonksClient SetVersion(string version)
        {
            Configuration.VersionState = version;
            init();
            return this;
        }

        /// <summary>
        /// Setter for "SportState" client state
        /// </summary>
        public SportmonksClient SetSport(string sport)
        {
            Configuration.SportState = sport;
            init();
            return this;
        }
    }
}
